
[[constraint]]
  name = "github.com/a8m/expect"
  branch = "master"

[[constraint]]
  name = "github.com/aymerick/raymond"
  version = "2.0.1"

[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.16.0"

[[constraint]]
  name = "github.com/fluffle/goirc"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  branch = "master"

[[constraint]]
  name = "github.com/pebbe/zmq4"
  branch = "master"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"
